name: leancode_forms_example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  leancode_forms:
    path: ..
  flutter_riverpod: ^2.4.7
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0

flutter:
  uses-material-design: true
